### PR TITLE
Remove yiisoft/yii-base-web

### PR DESCRIPTION
**Pull request by damasco**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by samdark** [comment]
Technically could be done but I need to re-check it. Likely it's a better idea to move some parts of the demo to common application base.

**Comment by damasco** [comment]
Both of them are projects, I think you should not include one in the other.

**Comment by samdark** [comment]
@hiqsol I think we need you :)

**Comment by thenotsoft** [comment]
I think everything is better in one package, since only one layout is planned, or is the basic and adavance layout planned?

**Comment by samdark** [comment]
No, there is no plan to have two application templates. The @hiqsol idea was that application template should be update-able i.e. you inherit from a template with your application.

**Comment by samdark** [comment]
Closing for now.

**Pull request closed without merging**
