### PR TITLE
Render now returns ResponseInterface instead of string

### PR DESCRIPTION
**Pull request by xepozz**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ❌
| Fixed issues  | #52

### CODE REVIEW

**Comment by roxblnfk** [comment]
I think it is wrong that the render method returns a `ResponseInterface`.
I suggest considering another way.
Let the `ActionCaller` wrap the string  value in a `ResponseInterface`.

**Comment by samdark** [comment]
> I think it is wrong that the render method returns a ResponseInterface.

I was thinking the same before taking into account that it's controller's render method, not a method of a View.

**Comment by roxblnfk** [comment]
> > I think it is wrong that the render method returns a ResponseInterface.
> 
> I was thinking the same before taking into account that it's controller's render method, not a method of a View.

It is also worth considering that this controller does not implement `MiddlewareInterface`, therefore it is not required to return a `ResponseInterface`. This also applies to other `Actions` passed to `ActionCaller`.

**Comment by samdark** [comment]
> Let the ActionCaller wrap the string value in a ResponseInterface.

What if you need headers as well? In case of `render()` returning `ResponseInterface` you can add headers after the rendering.

**Comment by roxblnfk** [comment]
> What if you need headers as well? In case of `render()` returning `ResponseInterface` you can add headers after the rendering.

Just like now, when we can manually create a Response.

But what if the Action specified in the ActionCaller returns a string rather than ResponseInterface?
What if I want to treat the rendered page as a string? Should I unpack it from Response? (I remind you that ResponseFactory writes a line to a tmp file when creating a stream)
I would be glad to see a separate method like `wrapToResponse ()`, but not so that render transformed it as Response by default

**Comment by yiiliveext** [comment]
> What if I want to treat the rendered page as a string? Should I unpack it from Response? (I remind you that ResponseFactory writes a line to a tmp file when creating a stream)

You still can do it, just render it manually
```php
$content = $this->view->render($view, $parameters, $this);
$bodyText = $this->renderContent($content);
```

**Comment by samdark** [comment]
Let's have it. We're likely refactor base controllers in something else anyway: https://github.com/yiisoft/yii-demo/issues/53

@xepozz thanks!

**Pull request merged**
