### PR TITLE
Subfolder support

### PR DESCRIPTION
**Pull request by roxblnfk**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | https://github.com/yiisoft/yii-demo/issues/11 https://github.com/yiisoft/yii-demo/issues/35 https://github.com/yiisoft/view/issues/46

This PR works only with https://github.com/yiisoft/yii-web/pull/194 , https://github.com/yiisoft/router/pull/13 and https://github.com/yiisoft/router-fastroute/pull/5

### CODE REVIEW

**Comment by samdark** [comment]
Looks good overall but check https://github.com/yiisoft/router/pull/13 please.

**Comment by roxblnfk** [comment]
https://github.com/yiisoft/view/issues/46

**Comment by samdark** [comment]
I've actually meant https://github.com/yiisoft/router/pull/14 :)

**Comment by samdark** [comment]
Merged everything. Thank you very much!

**Pull request merged**
