### PR TITLE
Move original request to container

### PR DESCRIPTION
**Pull request by yiiliveext**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️

### CODE REVIEW

**Comment by samdark** [comment]
What's the use case for it? That is original request that is not modified by any middleware.

**Comment by yiiliveext** [comment]
> What's the use case for it? That is original request that is not modified by any middleware.

See https://github.com/yiisoft/di/pull/120

**Comment by yiiliveext** [comment]
Maybe it makes sense to move the part from `config/web.php` to the `yii-web` package.

**Comment by samdark** [comment]
@yiiliveext I know it's useful for https://github.com/yiisoft/di/pull/120 as is but it's very confusing in general.

**Pull request closed without merging**
