### PR TITLE
Moved all files of the Contract into one directory

### PR DESCRIPTION
**Pull request by githubjeka**
Checked the ability to place Contract code in one place.

image

### CODE REVIEW

**Comment by samdark** [comment]
Looks like it fails tests.

**Comment by githubjeka** [comment]
Probably ref #289

Can you restart tests for this pull request?

**Comment by githubjeka** [comment]
Ref #292

**Comment by samdark** [comment]
Merged that one.

**Comment by samdark** [comment]
The approach is good but there's an inconvenience with Psalm exclude patterns: https://github.com/vimeo/psalm/issues/5721

**Review by samdark — APPROVED** [review]
But need to deal with Psalm somehow...

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
👍

**Pull request merged**
