### PR TITLE
Simplify parameters

### PR DESCRIPTION
**Pull request by rustamwin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ?
| Fixed issues  | -

### CODE REVIEW

**Comment by thenotsoft** [comment]
Your version works with both `'test'.key' => 'value'` and `'test' => ['key' => 'value']` ?

**Comment by rustamwin** [comment]
> Your version works with both 'test'.key' => 'value' and 'test' => ['key' => 'value'] ?

Yes. It works as well

**Comment by thenotsoft** [comment]
I'm not sure. When calling `->get('test.key')` in the first case it will return value, in seconda case will return null or default.

**Comment by roxblnfk** [comment]
> I'm not sure. When calling `->get('test.key')` in the first case it will return value, in seconda case will return null or default.

https://github.com/yiisoft/arrays/blob/64c6972bdd6fb804e92f70aca30202630b719635/src/ArrayHelper.php#L169

**Comment by thenotsoft** [comment]
> > I'm not sure. When calling `->get('test.key')` in the first case it will return value, in seconda case will return null or default.
> 
> https://github.com/yiisoft/arrays/blob/64c6972bdd6fb804e92f70aca30202630b719635/src/ArrayHelper.php#L136

Yes, you're right, I didn’t look at the sources of the method (

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
